<#
 Independent Script: Step 2.2 - Filter and Purge Pseudo-Labels
 
 Based on the 'readme_IFT.md' description, this script filters the pseudo-labels
 generated by 'yolo predict' and copies the high-quality samples to
 the 'train_pseudo' folder for the next training stage.
#>

# --- Configurable Parameters ---
param (
    # (Required) Which round of pseudo-labels are we processing?
    [int]$Round = 1,
    
    # (Required) Confidence score filter threshold (e.g., 0.80)
    [double]$ConfidenceThreshold = 0.80,
    
    # (Optional) Enable the "Advanced Area Filter" mentioned in the README?
    [switch]$EnableAreaFilter = $false,
    
    # (Optional) Minimum pixel area for the area filter (e.g., 8x8 = 64)
    [int]$MinPixelArea = 64,
    
    # (Optional) Image size used for area calculation (should match the 'imgsz' from predict)
    [int]$ImageSize = 416
)

# --- Environment Setup ---
chcp 65001 > $null
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = "Stop"

# --- Helper Function (from run_yolo12_semi_loop_full.ps1) ---
function Get-FirstExistingImagePath([string]$dir, [string]$stem) {
    # Check for .jpg, .jpeg, .png, .bmp
    $extensions = @(".jpg", ".jpeg", ".png", ".bmp")
    foreach ($ext in $extensions) {
        # Construct the full path for the candidate image file
        $candidate_path = Join-Path -Path $dir -ChildPath ($stem + $ext)
        # If the file exists, return the path immediately
        if (Test-Path -Path $candidate_path -PathType Leaf) {
            return $candidate_path
        }
    }
    # If no matching image file is found after checking all extensions, return null
    return $null
}

# --- Step 1: Path Resolution (from run_yolo12_semi_loop_full.ps1) ---
$BASE = Split-Path -Parent $MyInvocation.MyCommand.Definition
Write-Host "Script Base Directory: $BASE"

$DATASET_DEFAULT = Join-Path $BASE "dataset\wildlife"
$DATASET_ALT = Join-Path $BASE "datasets\wildlife"
if (Test-Path $DATASET_ALT) {
    $DATASET = $DATASET_ALT
}
elseif (Test-Path $DATASET_DEFAULT) {
    $DATASET = $DATASET_DEFAULT
}
else {
    Write-Host "ERROR: Could not find 'dataset\wildlife' or 'datasets\wildlife' folder."
    exit 1
}

# --- Step 2: Define Source and Destination Paths ---
$RUNS = Join-Path $BASE "runs"

# Source (Input): 6-column pseudo-labels generated by 'yolo predict'
$SRC_LABELS = Join-Path $RUNS ("pseudo\round{0}\labels" -f $Round)
# Source (Input): Original unlabeled images
$UNLABELED_IMG_DIR = Join-Path $DATASET "images\unlabeled"

# Destination (Output): Cleaned 5-column labels
$DEST_LABELS = Join-Path $DATASET "labels\train_pseudo"
# Destination (Output): Corresponding images
$DEST_IMAGES = Join-Path $DATASET "images\train_pseudo"

# Ensure destination directories exist
New-Item -ItemType Directory -Force -Path $DEST_LABELS, $DEST_IMAGES | Out-Null

# --- Step 3: Execute Filtering, Purging, and Saving ---

Write-Host ""
Write-Host "==== [Executing Step 2.2] Filtering Pseudo-Labels (Round $Round) ===="
Write-Host "Source (Input): $SRC_LABELS"
Write-Host "Destination (Output): $DEST_LABELS (and $DEST_IMAGES)"
Write-Host "---"
Write-Host "Filter Condition 1: Confidence (Conf) >= $ConfidenceThreshold"
if ($EnableAreaFilter) {
    Write-Host "Filter Condition 2: Area >= $MinPixelArea px (based on $ImageSize px image)"
} else {
    Write-Host "Filter Condition 2: Area Filter [Disabled]"
}
Write-Host "---"

if (-not (Test-Path $SRC_LABELS)) {
    Write-Host "ERROR: Source labels directory not found: $SRC_LABELS"
    Write-Host "Please run 'yolo predict ... save_txt=True save_conf=True' (Step 2.1) first."
    exit 1
}

# Clean destination directories to avoid mixing old pseudo-labels
Write-Host "Cleaning destination directories $DEST_LABELS and $DEST_IMAGES ..."
Get-ChildItem -Path $DEST_LABELS -Filter *.txt | Remove-Item -Force
Get-ChildItem -Path $DEST_IMAGES -Include *.jpg, *.jpeg, *.png, *.bmp | Remove-Item -Force

$kept_files = 0
$kept_boxes = 0
$total_boxes = 0

# Iterate over all .txt label files generated by predict
$labelFiles = Get-ChildItem -Path $SRC_LABELS -Filter *.txt -Recurse

# Use a 'foreach' loop instead of a pipeline (More robust)
foreach ($file in $labelFiles) {
    
    # Read all lines (bounding boxes)
    $all_lines = Get-Content $file.FullName
    $total_boxes += $all_lines.Count
    
    # --- Execute Filtering (README Points 2 & 3) ---
    $filtered_lines = $all_lines | Where-Object {
        $p = ($_ -split '\s+')
        
        # Check 1: Must be 6-column format (cls x y w h conf)
        if ($p.Count -lt 6) { return $false }
        
        # Check 2: Confidence Score Filter (README Point 2)
        $conf = [double]$p[5]
        $conf_ok = ($conf -ge $ConfidenceThreshold)
        if (-not $conf_ok) { return $false }
        
        # Check 3: (Advanced) Area Filter (README Point 3)
        if ($EnableAreaFilter) {
            $w_rel = [double]$p[3]
            $h_rel = [double]$p[4]
            # Convert relative w/h to absolute pixel area
            $area = ($w_rel * $ImageSize) * ($h_rel * $ImageSize)
            
            $area_ok = ($area -ge $MinPixelArea)
            if (-not $area_ok) { return $false }
        }
        
        # All checks passed
        return $true
    }
    
    # If any bounding boxes in this file passed the filter
    if ($filtered_lines) {
        
        # --- Format Purging (README Point 4) ---
        $outTxt = Join-Path $DEST_LABELS $file.Name
        $cleaned_lines = $filtered_lines | ForEach-Object { 
            # Take only the first 5 columns (cls x y w h) and rejoin
            ($_.Split(' '))[0..4] -join ' ' 
        }
        
        # --- Save (README Point 5) ---
        # Save the cleaned 5-column .txt label file
        $cleaned_lines | Set-Content -Path $outTxt -Encoding utf8
        
        # Find and copy the corresponding image file
        $imgPath = Get-FirstExistingImagePath -dir $UNLABELED_IMG_DIR -stem $file.BaseName
        if ($imgPath) {
            Copy-Item -Path $imgPath -Destination $DEST_IMAGES -Force
            $kept_files++
            $kept_boxes += $cleaned_lines.Count
        } else {
            # If the corresponding image is not found, delete the orphaned label file
            Write-Host "WARNING: Could not find corresponding image for $($file.BaseName). Deleting label."
            Remove-Item $outTxt -Force
        }
    }
}

Write-Host "---"
Write-Host "✅ Filtering Complete."
Write-Host "Total bounding boxes processed: $total_boxes"
Write-Host "Bounding boxes kept: $kept_boxes"
Write-Host "Image/Label files kept: $kept_files"
